# Generated by Django 5.1.3 on 2024-11-18 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritualUS', '0003_address_order_product_producttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('candle', 'CANDLE'), ('aromatherapy', 'AROMATHERAPY'), ('jewelry', 'JEWELRY'), ('decoration', 'DECORATION')], default='candle', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='category',
            field=models.CharField(choices=[('candle', 'CANDLE'), ('aromatherapy', 'AROMATHERAPY'), ('jewelry', 'JEWELRY'), ('decoration', 'DECORATION')], default='candle', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='ritualUS.producttype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='ritualUS.address'),
        ),
    ]
