# Generated by Django 5.1.3 on 2024-11-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritualUS', '0004_order_address_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED')], default='pending', max_length=50),
        ),
    ]
