# Generated by Django 5.1.1 on 2024-11-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ritualUS', '0004_create_order_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
