# Generated by Django 5.1.3 on 2024-12-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritualUS', '0005_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('confirmed', 'CONFIRMED'), ('in delivery', 'IN_DELIVERY'), ('delivered', 'DELIVERED')], default='pending', max_length=50),
        ),
    ]
