# Generated by Django 5.1.3 on 2024-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritualUS', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
