# Generated by Django 5.1.3 on 2024-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritualUS', '0006_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dni',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
