# Generated by Django 5.1.1 on 2024-12-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ritualUS', '0007_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.FloatField(default=5.0),
        ),
    ]
